#!/usr/bin/env bash

docker exec kafkainteractivequeriestest_kafka_1 bash -c "echo $2 | bin/kafka-console-producer.sh --broker-list kafka:9092 --topic $1 --property parse.key=true --property key.separator=,"

exit 0